//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDWFileHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOWN_PAI
    {
        public string FLOWN_FLT_ID { get; set; }
        public System.DateTime FLOWN_SEG_DEP_DATE { get; set; }
        public string FLOWN_STN_FR_CD { get; set; }
        public string FLOWN_STN_TO_CD { get; set; }
        public string FLOWN_BKG_CL { get; set; }
        public string FLOWN_SVC_CL { get; set; }
        public string OPR_AIRL_CD { get; set; }
        public string PNR_NO { get; set; }
        public string PSGR_FIRST_NM { get; set; }
        public string PSGR_LAST_NM { get; set; }
        public string MKT_FLT_ID { get; set; }
        public string AMADEUS_PNR { get; set; }
        public string GALILEO_PNR { get; set; }
        public string SABRE_PNR { get; set; }
        public string WORLDSPAN_PNR { get; set; }
        public string FQTV_AIRL_CD { get; set; }
        public string FQTV_CARD_TYPE { get; set; }
        public string FQTV_CARD_NO { get; set; }
        public string INFANT_IND { get; set; }
        public string PASSIVE_CREW_IND { get; set; }
        public string UMNR_IND { get; set; }
        public string REVENUE_IND { get; set; }
        public string PASSENGER_INDUSTRY_TYPE { get; set; }
        public string PASSENGER_TYPE { get; set; }
        public string TKT_TYPE_CODE { get; set; }
        public string TKT_DESG_AIRL_NO { get; set; }
        public string TKT_NO { get; set; }
        public string TKT_COUPON_NO { get; set; }
        public string IRREG_CD { get; set; }
        public string SOURCE_SYSTEM_ID { get; set; }
        public System.DateTime SIW_LOAD_TMS { get; set; }
        public string SIW_LOAD_ID { get; set; }
        public Nullable<System.DateTime> DOWNGRADE_TMS { get; set; }
        public Nullable<System.DateTime> UPGRADE_TMS { get; set; }
        public Nullable<System.DateTime> FLOWN_TMS { get; set; }
        public string FQTR_IND { get; set; }
        public string Hist_SPNR { get; set; }
    }
}
