//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDWFileHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRTRACK
    {
        public long AIRTRACKID { get; set; }
        public string FLTNO { get; set; }
        public string FLTSUF { get; set; }
        public System.DateTime DATOP { get; set; }
        public string STNON { get; set; }
        public string CCTYPME { get; set; }
        public string CCID { get; set; }
        public string DOCNO { get; set; }
        public string PAXNM { get; set; }
        public string SERVCL { get; set; }
        public string STNOFF { get; set; }
        public string BKGCLS { get; set; }
        public string MKTFLTNO { get; set; }
        public Nullable<System.DateTime> UPDTD_ON { get; set; }
        public Nullable<System.DateTime> INSERTED_ON { get; set; }
        public Nullable<int> CURR_STATUS { get; set; }
        public int DTID { get; set; }
        public string FBCODE { get; set; }
        public string COUPNO { get; set; }
        public string CMPID { get; set; }
        public string CMPCNSPNTYPE { get; set; }
        public string AUTOCHECKIN { get; set; }
        public string TICKETLESSCODE { get; set; }
        public string PSGRNT { get; set; }
        public string RES_PSGRNT { get; set; }
        public Nullable<long> AIRTRACKRESID { get; set; }
        public string SRC { get; set; }
    
        public virtual DATATRANSFERAIRTRACK DATATRANSFERAIRTRACK { get; set; }
        public virtual AIRTRACKRES AIRTRACKRES { get; set; }
    }
}
