//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDWFileHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLDSEG
    {
        public string AIRLDESG { get; set; }
        public string CARRIER { get; set; }
        public string CITYON { get; set; }
        public string CITYOFF { get; set; }
        public System.DateTime DATEFROM { get; set; }
        public System.DateTime DATETO { get; set; }
        public string DAYCHG { get; set; }
        public string LINEACD { get; set; }
        public string RSCS { get; set; }
    }
}
