//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDWFileHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATATRANSFERAIRTRACK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATATRANSFERAIRTRACK()
        {
            this.AIRTRACK = new HashSet<AIRTRACK>();
        }
    
        public int DELIVNO { get; set; }
        public Nullable<System.DateTime> DATE_OF_INSERT { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> TOTAL_REC { get; set; }
        public Nullable<System.DateTime> LST_UPDTD { get; set; }
        public string SRC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRTRACK> AIRTRACK { get; set; }
    }
}
