//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDWFileHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPAI_Coupon
    {
        public string AIRNO_JRNY { get; set; }
        public string FORMSENO_JRNY { get; set; }
        public string AIRNO_CONJ { get; set; }
        public string FORMSENO_CONJ { get; set; }
        public Nullable<short> SEQ_NO_DOC { get; set; }
        public Nullable<short> SEQ_NO_CONJ { get; set; }
        public string OWNER_ID { get; set; }
        public string AIRNO { get; set; }
        public string FORMSENO { get; set; }
        public string TYPEPAX { get; set; }
        public string TYPEIND { get; set; }
        public string TYPEDOC { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public string PNR { get; set; }
        public string PAXNAME { get; set; }
        public string MAIN_TYPE { get; set; }
        public string COUPON { get; set; }
        public string TRAFFIC_STATUS { get; set; }
        public string MISMATCH_STATUS { get; set; }
        public string EXCHANGE_STATUS { get; set; }
        public string INC_INVOICE_STATUS { get; set; }
        public string MANCL_STATUS { get; set; }
        public string PRINT_EXCH_STATUS { get; set; }
        public string REV_CPN { get; set; }
        public string PL_FROM { get; set; }
        public string PL_TO { get; set; }
        public string PL_CARRIER { get; set; }
        public string PL_FLIGHTNO { get; set; }
        public System.DateTime PL_FLIGHT_DATE { get; set; }
        public string BOOKING_CLASS { get; set; }
        public string FBTD { get; set; }
        public string FB_CLASS { get; set; }
        public string PAID_CLASS { get; set; }
        public string TRAD_BOOK_NBR { get; set; }
        public string FLOWN_MAIN_TYPE { get; set; }
        public string FLOWN_SUB_TYPE { get; set; }
        public string STRANDING { get; set; }
        public Nullable<short> NBR_PAX { get; set; }
        public string FLIGHT_NBR { get; set; }
        public Nullable<System.DateTime> FLIGHT_DATE { get; set; }
        public string ON_CITY { get; set; }
        public string OFF_CITY { get; set; }
        public string FB_GROUP { get; set; }
        public int EB_MBR_ID { get; set; }
        public string SOLD_MAIN_TYPE { get; set; }
    }
}
